name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up GCC, Make and Check
      run: sudo apt-get -y install gcc make check
    - name: Test using Check
      run: |
        make test
